[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
governance = "GwTF9DgiBrj8ezeJQNdubiTb4s3xmmXybHPCy3xgoHyJ"
membership = "FotEuL6PaHRDYuDmtqNrbbS52AwVX49MQSBjNwCWqRA4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/execai.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
