[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
governance = "6amHFyNoPK9MmbBKqthLMeoxTB4TV7CdVE5K4RXi1eDC"
membership = "FotEuL6PaHRDYuDmtqNrbbS52AwVX49MQSBjNwCWqRA4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
